version: '3'
services:
  api:
    build:
      context: ..
      dockerfile: ./docker/modules/api/Dockerfile
    ports:
      - "8080:8080"
    links:
      - "db:cassandra"
    command:  ["../../docker/wait-for-it.sh", "-t", "30", "db:9041", "--", "go-wrapper", "run"]
    environment:
      CASSANDRA_ADDRESS: cassandra

  db:
    build:
      context: ..
      dockerfile: ./docker/modules/db/Dockerfile
    environment:
      CASSANDRA_KEYSPACE: news_in_city
