version: '3'
services:
  api:
    build:
      context: ..
      dockerfile: ./docker/modules/api/Dockerfile
    volumes:
      - "../src/api:/go/src/github.com/HenriqueLimas/sample-feed-pwa/src/api"
    ports:
      - "8080:8080"
    links:
      - "db:cassandra"
      - "postgres:postgres"
    command:  ["../../docker/wait-for-it.sh", "-t", "30", "db:9041", "--", "fresh", "-c", "runner.conf", "main.go"]
    environment:
      CASSANDRA_ADDRESS: cassandra
      POSTGRES_ADDRESS: postgres://docker@postgres/news_in_city?sslmode=disable


  db:
    build:
      context: ..
      dockerfile: ./docker/modules/db/Dockerfile
    environment:
      CASSANDRA_KEYSPACE: news_in_city

  postgres:
    build:
      context: ..
      dockerfile: ./docker/modules/db/Postgres.Dockerfile
    environment:
      POSTGRES_DB: news_in_city
      POSTGRES_USER: docker
